import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'normalize.css';
import './globals.css';
import './reset.css';
import Header from '@/components/Header/Header';
import TanStackProvider from '@/providers/TanStackProvider/TanStackProvider';

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackProvider>
      <html lang="en" className={`${interSans.variable} `}>
        <body>
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </TanStackProvider>
  );
}
